name: Issue Review Greeting
description: A comment added everytime someone creates a issue 
author: @reeceatkinson
icon: book-open

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, thanks for taking the time to submit a issue! The collaborators will take a look soon.'
